pipeline {
    agent any
    triggers{
        cron '*/20 * * * *'
    }
    stages {
        stage('clone') {
            steps {
                git branch: 'main', url: 'https://github.com/sunnymca107/react-app.git'
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('Docker Build & push') {
            steps {
                sh 'docker build -t react-app .'
                sh 'docker tag react-app sunnymca107/react-app'
            }
        }
        stage('pull and run') {
            steps {
                sh 'docker pull sunnymca107/react-app'
                 sh 'docker rm -f react-app || true'
                sh 'docker run -d -p  sunnymca107/react-app'
            }
        }
    }
}

